"""Describe your change

Revision ID: 62dd264a955d
Revises: 71c1ed84c65b
Create Date: 2025-10-23 20:46:27.353900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62dd264a955d'
down_revision = '71c1ed84c65b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_fetch_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('next_fetch_time', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_column('next_fetch_time')
        batch_op.drop_column('last_fetch_time')

    # ### end Alembic commands ###
