"""Initial migration

Revision ID: 71c1ed84c65b
Revises: 
Create Date: 2025-09-25 19:24:00.356619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71c1ed84c65b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('newdevices',
    sa.Column('device_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('device_name', sa.String(length=100), nullable=False),
    sa.Column('device_code', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('device_id', name=op.f('pk_newdevices')),
    sa.UniqueConstraint('device_code', name=op.f('uq_newdevices_device_code'))
    )
    op.create_table('users',
    sa.Column('userId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=70), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=True),
    sa.Column('google_id', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('userId', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email')),
    sa.UniqueConstraint('google_id', name=op.f('uq_users_google_id'))
    )
    op.create_table('videos',
    sa.Column('video_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('video_link', sa.String(length=200), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.userId'], name=op.f('fk_videos_user_id_users')),
    sa.PrimaryKeyConstraint('video_id', name=op.f('pk_videos'))
    )
    op.create_table('devices',
    sa.Column('device_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('device_code', sa.String(length=100), nullable=False),
    sa.Column('device_token', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('current_video_id', sa.Integer(), nullable=True),
    sa.Column('playback_state', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['current_video_id'], ['videos.video_id'], name=op.f('fk_devices_current_video_id_videos')),
    sa.ForeignKeyConstraint(['user_id'], ['users.userId'], name=op.f('fk_devices_user_id_users')),
    sa.PrimaryKeyConstraint('device_id', name=op.f('pk_devices')),
    sa.UniqueConstraint('device_code', name=op.f('uq_devices_device_code')),
    sa.UniqueConstraint('device_token', name=op.f('uq_devices_device_token'))
    )
    op.create_table('schedule_videos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('schedule_group_id', sa.BigInteger(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.video_id'], name=op.f('fk_schedule_videos_video_id_videos')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_schedule_videos'))
    )
    with op.batch_alter_table('schedule_videos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_schedule_videos_schedule_group_id'), ['schedule_group_id'], unique=False)

    op.create_table('schedules',
    sa.Column('schedule_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('schedule_group_id', sa.BigInteger(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('repeat', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('play_mode', sa.String(length=20), nullable=True),
    sa.Column('download_status', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.device_id'], name=op.f('fk_schedules_device_id_devices')),
    sa.PrimaryKeyConstraint('schedule_id', name=op.f('pk_schedules'))
    )
    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_schedules_schedule_group_id'), ['schedule_group_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_schedules_schedule_group_id'))

    op.drop_table('schedules')
    with op.batch_alter_table('schedule_videos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_schedule_videos_schedule_group_id'))

    op.drop_table('schedule_videos')
    op.drop_table('devices')
    op.drop_table('videos')
    op.drop_table('users')
    op.drop_table('newdevices')
    # ### end Alembic commands ###
